import { Check, MoonStar } from "lucide-react";
import { useState } from "react";
import type { DailyReflection } from "@/domain/types";

export function ReflectionCard({ value, onComplete }: { value?: DailyReflection; onComplete: (r: DailyReflection) => void }) {
  const [open, setOpen] = useState(false); const [learned, setLearned] = useState(value?.learned ?? ""); const [spend, setSpend] = useState<DailyReflection["intentionalSpending"]>(value?.intentionalSpending ?? ""); const [tomorrow, setTomorrow] = useState(value?.tomorrow ?? "");
  if (!open) return <section className="card flex items-center justify-between gap-4 p-5 sm:p-7"><div className="flex gap-4"><div className="icon-button shrink-0"><MoonStar size={18}/></div><div><div className="eyebrow mb-2">Daily close</div><h2 className="text-lg font-medium">{value ? "Today is complete." : "Close the loop on today."}</h2><p className="mt-1 text-xs text-white/35">A quiet reflection. Less than two minutes.</p></div></div><button onClick={() => setOpen(true)} className={value ? "choice choice-active" : "primary-button"}>{value ? <><Check size={13}/> Review</> : "Begin"}</button></section>;
  return <section className="card p-5 sm:p-7"><div className="eyebrow mb-6"><MoonStar size={13}/> Daily close</div><div className="space-y-5"><label className="block"><span className="label">What did you learn today?</span><input className="input" value={learned} onChange={e => setLearned(e.target.value)} placeholder="One small thing is enough"/></label><div><span className="label">Did you spend intentionally?</span><div className="flex gap-2">{(["yes","mostly","no"] as const).map(v => <button key={v} onClick={() => setSpend(v)} className={`choice capitalize ${spend === v ? "choice-active" : ""}`}>{v}</button>)}</div></div><label className="block"><span className="label">What will you carry into tomorrow?</span><input className="input" value={tomorrow} onChange={e => setTomorrow(e.target.value)} placeholder="A thought, intention, or reminder"/></label><button disabled={!learned && !tomorrow && !spend} onClick={() => { onComplete({ learned, intentionalSpending: spend, tomorrow }); setOpen(false); }} className="primary-button w-full disabled:opacity-30">Complete today</button></div></section>;
}
