"use client";
import { Cloud, CloudOff, RefreshCw } from "lucide-react"; import { ProgressRing } from "@/components/ui/progress-ring"; import { WordCard } from "./word-card"; import { MoodCard } from "./mood-card"; import { MoneyCard } from "./money-card"; import { ReflectionCard } from "./reflection-card"; import { dailyIndex, moneyTips, words } from "@/data/daily-content"; import { friendlyDate } from "@/lib/date"; import type { DayRecord } from "@/domain/types"; import type { SyncStatus } from "@/hooks/use-daily-records";
type Store = { today: DayRecord; updateToday: (patch: Partial<DayRecord>) => void; ready: boolean; syncStatus: SyncStatus; pendingCount: number; sync: () => Promise<void> };
export function TodayView({ store, userName }: { store: Store; userName: string }) { const word = words[dailyIndex(words.length)], tip = moneyTips[dailyIndex(moneyTips.length)]; const done = [store.today.familiarWord !== undefined, !!store.today.mood, !!store.today.reflection].filter(Boolean).length; const progress = Math.round(done / 3 * 100); return <div className="mx-auto max-w-[1180px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><header className="mb-8 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-white/30">{friendlyDate()}</p><h1 className="mt-3 text-3xl font-medium tracking-tight sm:text-4xl">Good evening, {userName}.</h1><div className="mt-2 flex items-center gap-3"><p className="text-sm text-white/40">Take what you need from today.</p><SyncIndicator status={store.syncStatus} pending={store.pendingCount} retry={store.sync}/></div></div><div className="hidden items-center gap-3 sm:flex"><div className="text-right"><div className="text-xs text-white/55">Daily rhythm</div><div className="mt-1 text-[11px] text-white/25">{done} of 3 moments</div></div><ProgressRing value={progress}/></div></header><div className="mb-5 flex items-center justify-between rounded-2xl border border-white/[.07] bg-white/[.02] p-4 sm:hidden"><div><div className="text-sm">Daily rhythm</div><div className="mt-1 text-xs text-white/30">{done} of 3 moments</div></div><ProgressRing value={progress}/></div><div className="grid items-start gap-4 lg:grid-cols-2"><WordCard word={word} familiar={store.today.familiarWord} onFamiliar={familiarWord => store.updateToday({ familiarWord })}/><MoodCard value={store.today.mood} onSave={mood => store.updateToday({ mood })}/><MoneyCard tip={tip}/><div className="space-y-4"><ReflectionCard value={store.today.reflection} onComplete={reflection => store.updateToday({ reflection, completedAt: new Date().toISOString() })}/><div className="hidden rounded-2xl border border-dashed border-white/[.07] p-5 lg:block"><p className="text-center text-xs text-white/25">There is no perfect day here. Showing up is enough.</p></div></div></div></div>; }

function SyncIndicator({ status, pending, retry }: { status: SyncStatus; pending: number; retry: () => Promise<void> }) {
  if (status === "synced") return <span title="Your entries are saved to the cloud" className="flex items-center gap-1 text-[10px] text-white/25"><Cloud size={12}/> Synced</span>;
  if (status === "syncing" || status === "loading") return <span className="flex items-center gap-1 text-[10px] text-white/30"><RefreshCw size={12} className="animate-spin"/> {pending ? `Saving ${pending}` : "Syncing"}</span>;
  return <button onClick={() => void retry()} title="Your edits are safe on this device and will retry automatically" className="flex items-center gap-1 text-[10px] text-[#d6b878]"><CloudOff size={12}/> {status === "offline" ? `${pending || ""} saved offline` : "Retry sync"}</button>;
}
